name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install tcl-dev libreadline-dev libffi-dev pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev xz-utils

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install yosys
      run: git clone https://github.com/YosysHQ/yosys; cd yosys; make -j2 ENABLE_CCACHE=1; sudo make install; cd ..

    - name: Build
      run: sudo make install

    - name: Download benchmarks
      run: bash test/download_benchmarks.sh

    - name: Test
      run: bash test/test_commands.sh

    - name: Run
      run: bash test/run_benchmarks.sh

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark_results.tar.xz
